### ISSUE TITLE
How can I use numbers_solver?

### ISSUE THREAD

**Issue by KS-spec** [sudarshanv01/catmap-mirror#1]
Hello,

I have installed catmap-mirror and ran test_solver.py with pytest, but I am unsure how to use the numbers_solver.
When using the conventional catmap, I believe we would write it like this:

mkm_file = 'input.mkm'
model = ReactionModel(setup_file=mkm_file)
model.output_variables += ['production_rate']#,'rate_control']
model.run()

How would I modify this code to use the numbers_solver?

**Comment by sudarshanv01** [comment]
Hello @KS-spec, to use the numbers solver, please use the `use_numbers_solver` flag. So your code would look something like this:
```
mkm_file = 'input.mkm'
model = ReactionModel(setup_file=mkm_file)
... # Other settings
model.use_numbers_solver = True
model.run()
```
Additionally, the `fix_x_star` may be turned on if you would like to fix the value of x_* (numbers of the empty site) to one.

**Comment by KS-spec** [comment]
Thank you very much!!
